# https://help.github.com/en/actions/language-and-framework-guides/building-and-testing-java-with-gradle
# https://help.github.com/en/actions/language-and-framework-guides/publishing-java-packages-with-gradle

name: Publish

on:
  push:
    branches:
      - main

jobs:
  build:
    # https://help.github.com/en/actions/reference/virtual-environments-for-github-hosted-runners
    # https://help.github.com/en/actions/configuring-and-managing-workflows/configuring-a-workflow#configuring-a-build-matrix
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - uses: gradle/actions/setup-gradle@v3

      - run: ./gradlew --continue build app:installShadowDist # TODO: app:nativeImage

      - name: Publish jar
        uses: actions/upload-artifact@v1
        if: runner.os == 'Linux'
        with:
          name: aidea-jar
          path: app/build/install/app-shadow/lib/aidea-all.jar

# TODO: enable after OSX fix
#      - name: Publish Linux binary
#        uses: actions/upload-artifact@v1
#        if: runner.os == 'Linux'
#        with:
#          name: aidea-linux
#          path: app/build/graal/aidea

# TODO: java.lang.TypeNotPresentException: Type org.graalvm.nativeimage.Platform$MACOS not present
# https://stackoverflow.com/questions/59717111/cannot-generate-native-image-using-graalvm-in-os-x-catalina
#      - name: Publish OSX binary
#        uses: actions/upload-artifact@v1
#        if: runner.os == 'macOS'
#        with:
#          name: aidea-macos
#          path: app/build/graal/aidea
